name: sklearnprod0
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - cython
  - cvxopt
  - lapack
  - cvxpy
  - scikit-learn
  - seaborn
  - graphviz
  - pip
  - jupyter_contrib_nbextensions
  - pandas
  - matplotlib
  - pip:
      - nose-timer
      - wheelhouse_uploader
      - nose
      - yapf
      - Wheel
      - numpy
      - scipy
      - graphviz
      - jupyter
      - pandas
      - pillow
      - graphviz
      - pydotplus
      - jupyterthemes
      - flake8
      - autopep8
      - xlrd
